service: labRegistro
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    DYNAMODB_TABLE: RegistroAcademico
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:us-east-1:*:table/RegistroAcademico

functions:
  # ==== PARCIALES ====
  createParcial:
    handler: src/handlers/parciales.create
    events:
      - http:
          path: parciales
          method: post
          cors: true

  getAllParciales:
    handler: src/handlers/parciales.getAll
    events:
      - http:
          path: parciales
          method: get
          cors: true

  getParcialById:
    handler: src/handlers/parciales.getById
    events:
      - http:
          path: parciales/{asignaturaId}/{parcialId}
          method: get
          cors: true

  updateParcial:
    handler: src/handlers/parciales.update
    events:
      - http:
          path: parciales/{asignaturaId}/{parcialId}
          method: put
          cors: true

  deleteParcial:
    handler: src/handlers/parciales.delete
    events:
      - http:
          path: parciales/{asignaturaId}/{parcialId}
          method: delete
          cors: true

  # ==== PRACTICAS ====
  createPractica:
    handler: src/handlers/practicas.create
    events:
      - http:
          path: practicas
          method: post
          cors: true

  getAllPracticas:
    handler: src/handlers/practicas.getAll
    events:
      - http:
          path: practicas
          method: get
          cors: true

  getPracticaById:
    handler: src/handlers/practicas.getById
    events:
      - http:
          path: practicas/{id}
          method: get
          cors: true

  updatePractica:
    handler: src/handlers/practicas.update
    events:
      - http:
          path: practicas/{id}
          method: put
          cors: true

  deletePractica:
    handler: src/handlers/practicas.delete
    events:
      - http:
          path: practicas/{id}
          method: delete
          cors: true

package:
  individually: true

resources:
  Resources:
    RegistroAcademicoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: RegistroAcademico
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
